### PR TITLE
update iron-list component to 3.1.0 (#104)

### PR DESCRIPTION
**Pull request by tomivirkki**
Cherry pick #104

### CODE REVIEW

**Comment by heruan** [comment]
Will this be on next 3.2.0 alpha?

**Comment by tomivirkki** [comment]
> Will this be on next 3.2.0 alpha?

Yes, it's already in `master` since https://github.com/vaadin/vaadin-iron-list-flow/commit/afec637152ede0911ce0a38c4615c2ca7ceeaa5c

You can also set `@polymer/iron-list` version to `3.1.0` in `package.json` in your Vaadin project to try out the fix.

**Comment by heruan** [comment]
> You can also set `@polymer/iron-list` version to `3.1.0` in `package.json` in your Vaadin project to try out the fix.

If I do this, I'm getting:

```
DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "iron-list" has already been used with this registry
```

**Comment by tomivirkki** [comment]
@heruan It means you have two versions of iron-list installed at the same time. Try cleaning up before starting: `rm -rf node_modules package-lock.json webpack.* target`

**Comment by heruan** [comment]
Thank you @tomivirkki I've tried that but still get the error. Notice that I'm testing this now in V16, so I'm doing `pnpm install @polymner/iron-list@3.1.0`, hope this is correct.

**Comment by heruan** [comment]
I've also tried to depend on `3.2-SNAPSHOT` but it still gets `iron-list@3.0.2` 😕

**Comment by mvysny** [comment]
@heruan Quoting Pekka Hyvonen: 
> The direct version added to package.json is the one that should take precedence over everything.
We've just recently made fixes related to this regarding transitive dependencies so you should ctually use the 14.2.2 to get the fixes

**Comment by heruan** [comment]
@mvysny and @pleku I was able to do so in V14, but as I said above I'm testing this on V16 now and adding to `package.json` fails with this client error:

```
DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "iron-list" has already been used with this registry
```

This happens even if I delete `node_modules`, `package.json` and `pnpm-lock.yaml`.

**Comment by tomivirkki** [comment]
Closing, V17 has the updated iron-list version.

**Pull request closed without merging**
