### PR TITLE
Update iron-list to use the new beforeClientResponse API

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Also add tests for detaching and reattaching, just like with Grid.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-iron-list-flow/24)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 148 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-iron-list-flow/24#-L6V9ccx8ohYUuV2EG_I:-L6V9ccx8ohYUuV2EG_J:biwda5d) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/e2e29d114c82a67b5af7ed7ef571850de652d250/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L148)):*
>  ui.getPage().executeJavaScript("window.ironListConnector.initLazy($0)",
>                 getElement());

same mistake here (as originally in Grid) : this should be inside `beforeClientResponse`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-iron-list-flow/24)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 148 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/24#-L6V9ccx8ohYUuV2EG_I:-L6VJ62yLD20loQFx2Jo:b-pg7ypv) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/e2e29d114c82a67b5af7ed7ef571850de652d250/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L148)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  ui.getPage().executeJavaScript("window.ironListConnector.initLazy($0)",
>                 getElement());

same mistake here (as originally in Grid) : this should be inside `beforeClientResponse`.
</blockquote></details>

This method is called from two different places. When the component is first created (inside the constructor), and every time it is attached.

Why two places instead of just when it is attached?

There are a lot of calls to the connector when the iron list (and Grid as well) is created, and to keep track of all of those by using `beforeClientResponse` made things a bit complex and unstable. The `beforeClientResponse` callbacks are executed before the `attachListener`  is called (so the script is not initialized before it is used).

So for now I did a good enough solution that we can optimize later. The current drawback is that the `initLazy` is called twice when the list/grid is first created. The script was updated to prevent double initialization (so we don't need to send extra data). And that's it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/24)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 148 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/24#-L6V9ccx8ohYUuV2EG_I:-L6VN4W8YOp9N1RmwQHd:b-j56al4) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/e2e29d114c82a67b5af7ed7ef571850de652d250/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L148)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This method is called from two different places. When the component is first created (inside the constructor), and every time it is attached.

Why two places instead of just when it is attached?

There are a lot of calls to the connector when the iron list (and Grid as well) is created, and to keep track of all of those by using `beforeClientResponse` made things a bit complex and unstable. The `beforeClientResponse` callbacks are executed before the `attachListener`  is called (so the script is not initialized before it is used).

So for now I did a good enough solution that we can optimize later. The current drawback is that the `initLazy` is called twice when the list/grid is first created. The script was updated to prevent double initialization (so we don't need to send extra data). And that's it.
</blockquote></details>

Don't see a problem:
then please call this method not via the 
`getElement().getNode().runWhenAttached(this::initConnector);` in the CTOR
but via the
`getElement().getNode().runWhenAttached( ui-> ui.beforeClientResponse(this, this::initConnector);`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/24)*

**Comment by gilberto-torrezan** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 148 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/24#-L6V9ccx8ohYUuV2EG_I:-L6VOv7DQeazX_2E9EMI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/e2e29d114c82a67b5af7ed7ef571850de652d250/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L148)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Don't see a problem:
then please call this method not via the 
`getElement().getNode().runWhenAttached(this::initConnector);` in the CTOR
but via the
`getElement().getNode().runWhenAttached( ui-> ui.beforeClientResponse(this, this::initConnector);`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/24)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/24)*

**Pull request merged**
