### PR TITLE
Add support for placeholder items.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-iron-list-flow/16)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1QnWJtOxi12FUGOlgB:-L1QnWJtOxi12FUGOlgC:b1ckbpx) (no related file):*
Do I understand right that there is already an IT test for placeholder, you just changed the API for it?

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 229 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1Qm5HcEn9jMAFprS95:-L1Qm5HcEn9jMAFprS96:b-2fns5i) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/7962c59e714cca02c056943854b27f4b406f5261/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L229)):*
> 100px

may be it would be good to emphasize this value (like a code, bold or whatever) to distinguish it from other text.
Not a blocker.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 267 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1Qn2EoHt80VudfEDWi:-L1Qn2EoHt80VudfEDWj:bfxmnvl) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/7962c59e714cca02c056943854b27f4b406f5261/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L267)):*
>  else {
>             if 

Can be combined into `else if` which reduces the number of nested blocks and complexity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16)*

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 236 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1QordMNt8P8w21V4fo:-L1QordNnfxPFkNslMl4:b69ue17) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/747e31990e6a23b83168791bb35166f48508ba9c/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L236)):*
> ```Java
>      *            loaded, not <code>null</code>
>      */
>     public void setPlaceholderTemplate(String placeholderTemplate) {
> ```

Looks like the possibility for a custom template is now removed. Would it not make sense to have both?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16)*

**Comment by gilberto-torrezan** [comment]
Review status: 2 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1QnWJtOxi12FUGOlgB:-L1RCHGGXmommk3F5S4Q:bqurd51) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Do I understand right that there is already an IT test for placeholder, you just changed the API for it?
</blockquote></details>

Have added a check for the specific part that was changed on the client-side.

A full check for the placeholder component and how it is rendered is quite complicated though.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 229 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1Qm5HcEn9jMAFprS95:-L1R2s3C3PKD_izn3xhs:b-896fix) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/7962c59e714cca02c056943854b27f4b406f5261/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L229)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> 100px

may be it would be good to emphasize this value (like a code, bold or whatever) to distinguish it from other text.
Not a blocker.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 236 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1QordMNt8P8w21V4fo:-L1R2ArgnP9so-dtO9jZ:btnq8bh) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/747e31990e6a23b83168791bb35166f48508ba9c/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L236)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Looks like the possibility for a custom template is now removed. Would it not make sense to have both?
</blockquote></details>

I excluded the template for placeholder because it was an workaround. IMO we should wait for DX tests to see whether it makes sense or not to have a template for placeholders.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 267 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1Qn2EoHt80VudfEDWi:-L1R2quBHlrmAEkJU2um:b-896fix) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/7962c59e714cca02c056943854b27f4b406f5261/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L267)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  else {
>             if 

Can be combined into `else if` which reduces the number of nested blocks and complexity
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16)*

**Comment by ahie** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[src/main/java/com/vaadin/flow/component/ironlist/IronList.java, line 236 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16#-L1QordMNt8P8w21V4fo:-L1RDhDPrti0K-LY848D:bb6mt9b) ([raw file](https://github.com/vaadin/vaadin-iron-list-flow/blob/747e31990e6a23b83168791bb35166f48508ba9c/src/main/java/com/vaadin/flow/component/ironlist/IronList.java#L236)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I excluded the template for placeholder because it was an workaround. IMO we should wait for DX tests to see whether it makes sense or not to have a template for placeholders.
</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-iron-list-flow/16)*

**Pull request merged**
